repos:
# Some generally used hooks for sanity-check
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: no-commit-to-branch
        args: [--branch, master]

# Applies formating and linting to CMake files
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
        types: [file]
        files: (\.cmake|CMakeLists.txt)(.in)?$
    -   id: cmake-lint
        types: [file]
        files: (\.cmake|CMakeLists.txt)(.in)?$

# Changes tabs to spaces
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
    -   id: remove-tabs

# Applies static-analysis tools
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: clang-format
        args: [-i]
    -   id: clang-tidy
    -   id: cpplint
    -   id: cppcheck
        args: [--template=gcc, --std=c++11,
               --enable=style,performance,warning,portability, --inline-suppr,
               --suppress=internalAstError, --suppress=unmatchedSuppression,
               --inconclusive]
