language: cpp
dist: xenial
sudo: required
git:
    submodules: false
matrix: 
  include:
    - os: linux
      env: PYTHON=3.6

before_install:
  - ./scripts/setup_dependencies.sh
  - |
    if [ -n "$PYTHON" ]; then
      pip install --user --upgrade pip virtualenv
      virtualenv -p $(which python3) venv
      source venv/bin/activate
    fi
script:
  - |
    if [ -n "$PYTHON" ]; then
      pip install setuptools numpy
      python setup.py build
    fi