language: cpp
dist: xenial
sudo: required
matrix: 
  include:
    - os: linux
      env: PYTHON=3.6

before_install:
  - sudo apt-get install make cmake pkg-config
  - sudo apt-get install libassimp-dev libglfw3-dev libglew-dev
  - |
    if [ -n "$PYTHON" ]; then
      pip install --user --upgrade pip virtualenv
      virtualenv -p python$PYTHON venv
      source venv/bin/activate
install:
  - |
    if [ -n "$PYTHON" ]; then
      pip install setuptools numpy
      python setup.py build