[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "ninja",
  "cmake>=3.15",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
