#include <loco/core/simulation_t.hpp>

// Disable warnings generated by the Bullet codebase
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wsign-conversion"
#pragma clang diagnostic ignored "-Wold-style-cast"
#pragma clang diagnostic ignored "-Wdouble-promotion"
#pragma clang diagnostic ignored "-Wimplicit-float-conversion"
#pragma clang diagnostic ignored "-Wcast-align"
#endif

#if defined(LOCO_BULLET_ENABLED)
#include <loco/backends/bullet/simulation_impl_bullet.hpp>
#endif

#if defined(LOCO_MUJOCO_ENABLED)
#include <loco/backends/mujoco/simulation_impl_mujoco.hpp>
#endif

#if defined(LOCO_DART_ENABLED)
#include <loco/backends/dart/simulation_impl_dart.hpp>
#endif

#include <stdexcept>

namespace loco {
namespace core {

auto Simulation::Init() -> void {
    switch (m_BackendType) {
        case eBackendType::NONE:
            m_BackendImpl = std::make_unique<SimulationImplNone>(m_Scenario);
            break;
        case eBackendType::BULLET:
#if defined(LOCO_BULLET_ENABLED)
            m_BackendImpl =
                std::make_unique<bullet::SimulationImplBullet>(m_Scenario);
#endif
            break;
        case eBackendType::MUJOCO:
#if defined(LOCO_MUJOCO_ENABLED)
            m_BackendImpl =
                std::make_unique<mujoco::SimulationImplMujoco>(m_Scenario);
#endif
            break;
        case eBackendType::DART:
#if defined(LOCO_DART_ENABLED)
            m_BackendImpl =
                std::make_unique<dart::SimulationImplDart>(m_Scenario);
#endif
            break;
    }

    if (m_BackendImpl != nullptr) {
        m_BackendImpl->Init();
    }

    // TODO(wilbert): initialize all objects in this scenario
}

auto Simulation::Reset() -> void {
    if (m_BackendImpl != nullptr) {
        m_BackendImpl->Reset();
    }
}

auto Simulation::Step(Scalar step) -> void {
    if (m_BackendImpl != nullptr) {
        m_BackendImpl->Step(step);
    }
}

auto Simulation::SetTimeStep(Scalar step) -> void {
    m_TimeStep = step;
    if (m_BackendImpl != nullptr) {
        m_BackendImpl->SetTimeStep(step);
    }
}

auto Simulation::SetGravity(const Vec3& gravity) -> void {
    m_Gravity = gravity;
    if (m_BackendImpl != nullptr) {
        m_BackendImpl->SetGravity(gravity);
    }
}

auto Simulation::impl() -> SimulationImpl& {
    if (m_BackendImpl == nullptr) {
        throw std::runtime_error(
            "Simulation >>> Must initialize the simulation first");
    }
    return *m_BackendImpl;
}

auto Simulation::impl() const -> const SimulationImpl& {
    if (m_BackendImpl == nullptr) {
        throw std::runtime_error(
            "Simulation >>> Must initialize the simulation first");
    }
    return *m_BackendImpl;
}

}  // namespace core
}  // namespace loco

#if defined(__clang__)
#pragma clang diagnostic pop  // NOLINT
#endif
